---
title: "Replication - Lagged Variables and Fixed Effects"
author: "Adopted from Gamm and Kousser (2021)"
output: pdf_document
---

```{r, include = F}
# load packages
library(lfe)
library(lmtest)
library(plm)
library(stargazer)
library(tidyverse)

# read in data
df <- read.delim("PoliticsProsperityJune2021.tab")
```

# Table 1 with Lagged Variables and State Fixed Effects
```{r, include = F}
# subset for Lag Table 1
df_tab1 <- df %>%
  filter(year > 1870 & year < 1990)

df_lag1 <- df_tab1 %>%
  select(Education_pc, HealthSewerSanitation_pc, Transportation_pc,
         leg_party_competition, Statewide_Competition, house_dem, 
         senate_dem, gov_dem, CPI_per_capita_income, foreignborn_pct, black_pct, 
         othernonwhite_pct, urban_pct, state, year, year_1890, year_1900, year_1910,
         year_1920, year_1930, year_1940, year_1950, year_1960, year_1970, year_1980)

# create lagged variables
df_lag1 <- df_lag1 %>%
  mutate(lag_Education_pc = ifelse(year != 1880, lag(Education_pc), NA)) %>%
  mutate(lag_Health_pc = ifelse(year != 1880, lag(HealthSewerSanitation_pc), NA)) %>%
  mutate(lag_Transportation_pc = ifelse(year != 1880, lag(Transportation_pc), NA))

# regress Lag Table 1, Model 1
lag1_mod1 <- plm(Education_pc ~ lag_Education_pc + leg_party_competition +
            year_1890 + year_1900 + year_1910 + year_1920 + year_1930 + year_1940 + 
            year_1950 + year_1960 + year_1970 + year_1980, index = "state", data = df_lag1)
lag1_mod1_se <- coeftest(lag1_mod1, function(x) vcovHC(x, type = 'sss'))

# regress Lag Table 1, Model 2
lag1_mod2 <- plm(Education_pc ~ lag_Education_pc + leg_party_competition +
            Statewide_Competition + house_dem + senate_dem + gov_dem + 
            CPI_per_capita_income + foreignborn_pct + black_pct + 
            othernonwhite_pct + urban_pct + year_1890 + year_1900 + 
            year_1910 + year_1920 + year_1930 + year_1940 + 
            year_1950 + year_1960 + year_1970 + year_1980, 
            index = "state", data = df_lag1)
lag1_mod2_se <- coeftest(lag1_mod2, function(x) vcovHC(x, type = 'sss'))

# regress Lag Table 1, Model 3
lag1_mod3 <- plm(HealthSewerSanitation_pc ~ lag_Health_pc + leg_party_competition +
            year_1890 + year_1900 + year_1910 + year_1920 + year_1930 + year_1940 + 
            year_1950 + year_1960 + year_1970 + year_1980, index = "state", data = df_lag1)
lag1_mod3_se <- coeftest(lag1_mod3, function(x) vcovHC(x, type = 'sss'))

# regress Lag Table 1, Model 4
lag1_mod4 <- plm(HealthSewerSanitation_pc ~ lag_Health_pc + leg_party_competition +
            Statewide_Competition + house_dem + senate_dem + gov_dem + 
            CPI_per_capita_income + foreignborn_pct + black_pct + 
            othernonwhite_pct + urban_pct + year_1890 + year_1900 + 
            year_1910 + year_1920 + year_1930 + year_1940 + 
            year_1950 + year_1960 + year_1970 + year_1980, 
            index = "state", data = df_lag1)
lag1_mod4_se <- coeftest(lag1_mod4, function(x) vcovHC(x, type = 'sss'))

# regress Lag Table 1, Model 5
lag1_mod5 <- plm(Transportation_pc ~ lag_Transportation_pc + leg_party_competition +
            year_1890 + year_1900 + year_1910 + year_1920 + year_1930 + year_1940 + 
            year_1950 + year_1960 + year_1970 + year_1980, index = "state", data = df_lag1)
lag1_mod5_se <- coeftest(lag1_mod5, function(x) vcovHC(x, type = 'sss'))

# regress Lag Table 1, Model 6
lag1_mod6 <- plm(Transportation_pc ~ lag_Transportation_pc + leg_party_competition +
            Statewide_Competition + house_dem + senate_dem + gov_dem + 
            CPI_per_capita_income + foreignborn_pct + black_pct + 
            othernonwhite_pct + urban_pct + year_1890 + year_1900 + 
            year_1910 + year_1920 + year_1930 + year_1940 + 
            year_1950 + year_1960 + year_1970 + year_1980, 
            index = "state", data = df_lag1)
lag1_mod6_se <- coeftest(lag1_mod6, function(x) vcovHC(x, type = 'sss'))
```

```{r, results = "asis"}
# print Lagged Table 1
stargazer(lag1_mod1_se, lag1_mod2_se, lag1_mod3_se, 
          lag1_mod4_se, lag1_mod5_se, lag1_mod6_se,
          header = F, type = "latex", digits = 2, style = "apsr",
          title = "Party Competition Does NOT Predict Human Capital and Infrastructure Spending, 1880-1980",
          column.labels = c("Education spending", "Health spending",
                            "Transportation spending"),
          column.separate = c(2, 2, 2),
          covariate.labels = c("Lagged education spending", "Lagged health spending",
                               "Lagged transportation spending", 
                               "Legislative party competition",
                               "Electoral competition", "Democratic house",
                               "Democratic senate", "Democratic governor",
                               "Income per capita", "Foreign-born percentage",
                               "Black percentage", "Other nonwhite percentage", 
                               "Urban population percentage"),
          omit = c("Constant", "year_1890", "year_1900", "year_1910", 
                   "year_1920", "year_1930", "year_1940", "year_1950", 
                   "year_1960", "year_1970", "year_1980"),
          add.lines = list(c("State fixed effects", 
                             "included", "included", "included", 
                             "included", "included", "included"),
                           c("Year fixed effects",
                             "included", "included", "included", 
                             "included", "included", "included"),
                           c("Observations", "258", "249", "187", "182", "234", "228"),
                           c("R-Squared", "0.97", "0.98", "0.89", "0.92", "0.93", "0.94"),
                           c("Adj. R-Squared", "0.97", "0.97", "0.85", "0.87", "0.91", "0.91")))
```

\newpage

# Table 2 with Lagged Variables and State Fixed Effects
```{r, include = F}
# subset for overall Lag Table 2
df_lag2 <- df %>%
  select(infantmortality, at_birth_life_expectancy, graduation_combined, 
         illiteracy_proportional_30, Education_pc, HealthSewerSanitation_pc,
         leg_party_competition, Statewide_Competition, house_dem, 
         senate_dem, gov_dem, CPI_per_capita_income, foreignborn_pct, black_pct, 
         othernonwhite_pct, urban_pct, state, year, south)

# subset for Lag Table 2, Model 1
df_lag2_mod1 <- df_lag2 %>%
  mutate(lag_infantmortality = ifelse(year != 1880, lag(infantmortality), NA)) %>%
  filter(year >= 1930 & year < 2020)

# regress Lag Table 2, Model 1
lag2_mod1 <- plm(infantmortality ~ lag_infantmortality + HealthSewerSanitation_pc + 
                 CPI_per_capita_income + foreignborn_pct + black_pct + 
                 othernonwhite_pct + urban_pct + as.factor(year),
                 index = "state", data = df_lag2_mod1)
lag2_mod1_se <- coeftest(lag2_mod1, function(x) vcovHC(x, type = 'sss'))

# subset for Lag Table 2, Model 2
df_lag2_mod2 <- df_lag2 %>%
  filter(year >= 1880 & year <= 2010) %>%
  mutate(f3_at_birth_life_expectancy = dplyr::lead(at_birth_life_expectancy, 3)) %>%
  filter(year <= 1980)

# regress Lag Table 2, Model 2
lag2_mod2 <- plm(f3_at_birth_life_expectancy ~ at_birth_life_expectancy +
                   HealthSewerSanitation_pc + CPI_per_capita_income +
                   foreignborn_pct + black_pct + othernonwhite_pct +
                   urban_pct + as.factor(year),
                 index = "state", data = df_lag2_mod2)
lag2_mod2_se <- coeftest(lag2_mod2, function(x) vcovHC(x, type = 'sss'))

# subset for Lag Table 2, Models 3 and 4
df_lag2_mod3 <- df_lag2 %>%
  filter(year >= 1880 & year <= 2010) %>%
  mutate(lag_graduation_combined = ifelse(year != 1880, lag(graduation_combined), NA)) %>%
  mutate(illiteracy_20 = lag(illiteracy_proportional_30))

# regress Lag Table 2, Model 3
lag2_mod3 <- plm(graduation_combined ~ lag_graduation_combined + Education_pc +
                   CPI_per_capita_income + foreignborn_pct + black_pct +
                   othernonwhite_pct + urban_pct + south + as.factor(year),
                 index = "state", data = df_lag2_mod3)
lag2_mod3_se <- coeftest(lag2_mod3, function(x) vcovHC(x, type = 'sss'))

# regress Lag Table 2, Model 4
# note: the lagged variable is the illiteracy rate 20 years later
lag2_mod4 <- plm(illiteracy_proportional_30 ~ illiteracy_20 + Education_pc +
                   CPI_per_capita_income + foreignborn_pct + black_pct +
                   othernonwhite_pct + urban_pct + south + as.factor(year),
                 index = "state", data = df_lag2_mod3)
lag2_mod4_se <- coeftest(lag2_mod4, function(x) vcovHC(x, type = 'sss'))
```

```{r, results = "asis"}
# print Lagged Table 2
stargazer(lag2_mod1_se, lag2_mod2_se, lag2_mod3_se, lag2_mod4_se,
          header = F, type = "latex", font.size = "tiny", style = "apsr",
          title = "Spending Levels Do NOT Predict Development, 1880-2010",
          column.labels = c("Infant mortality", 
                            "Life expectancy (30 years later)",
                            "High school completion", 
                            "Illiteracy rate (30 years later)"),
          covariate.labels = c("Lagged infant mortality", "Current life expectancy",
                               "Health spending per capita", 
                               "Lagged high school completion", "Illiteracy (20 years later)",
                               "Education spending per capita", "Income per capita",
                               "Foreign-born percentage", "Black percentage", 
                               "Other nonwhite percentage", "Urban population percentage"),
          omit = c("Constant", "south", "year"),
          add.lines = list(c("State fixed effects",
                             "included", "included", "included", "included"),
                           c("Year fixed effects",
                             "included", "included", "included", "included"),
                           c("Observations", "215", "181", "336", "134"),
                           c("R-Squared", "0.98", "0.99", "0.98", "0.72"),
                           c("Adjusted R-Squared", "0.98", "0.98", "0.97", "0.52")))
```